### DISCUSSION TITLE
Can't find instruction for ios deployment

### DISCUSSION THREAD

**Discussion by ezalorsara** [wzieba/AppCenter-Github-Action#38] [Q&A] [answered]
Example ios workflow
```

name: IOS

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: npm ci

      - run: npm test
        name: Run Test(Jest)

      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: actions/cache@v2
        with:
          path: ~/Library/Caches/CocoaPods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - uses: actions/cache@v2
        with:
          path: ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - run: yarn install --frozen-lockfile
      - run: pod install
        working-directory: ios

      - run: xcodebuild clean archive -workspace Epico.xcworkspace -scheme Epico -archivePath Epico.xcarchive CODE_SIGNING_ALLOWED=NO | xcpretty
        working-directory: ios

```

Question how to use : 
this AppCenter-Github-Action for ios build

since it only works in linux 

Container action is only supported on Linux

Thanks.
