### ISSUE TITLE
Container action is only supported on Linux

### ISSUE THREAD

**Issue by wcoder** [wzieba/AppCenter-Github-Action#18]
Github Actions Workflow:
```yml
    runs-on: macos-latest
    // ...
    - name: Upload to App Center
      uses: wzieba/AppCenter-Github-Action@v1.1.1
      with:
        appName: company/appname
        token: ${{secrets.app_center}}
        group: Testers
        file: build/app/outputs/apk/release/app-release.apk (or .ipa)
```

Actions output:

```
##[group***Run wzieba/AppCenter-Github-Action@v1.1.1
with:
  appName: company/appname
  token: ***
  group: Testers
  file: src/build/app/outputs/apk/release/app-release.apk
env:
  flutter_version: 1.17.5
  java_version: 12.x
  JAVA_HOME: /Users/runner/hostedtoolcache/jdk/12.0.2/x64
  JAVA_HOME_12.0.2_x64: /Users/runner/hostedtoolcache/jdk/12.0.2/x64
  FLUTTER_HOME: /Users/runner/hostedtoolcache/flutter/1.17.5-stable/x64
##[endgroup***
##[error***Container action is only supported on Linux
```

Seems like related with Docker: https://docs.github.com/en/actions/creating-actions/about-actions#types-of-actions

I propose to put on documentation some information about this constraint!
