### ISSUE TITLE
When Trying to upload an APK, *.apk doesn't work, It throws file not found error

### ISSUE THREAD

**Issue by kuwrom** [wzieba/AppCenter-Github-Action#51]
When the apk name contains version name, we can't just hard code the apk path/ file. How would it be possible to pass the file name

**Comment by MarcelReiter** [comment]
My workaround was the following:

```
- name: Get path of created apk
  id: retrieve-path
  run: echo "path=$(find app/build/outputs/apk/ -type f -name '*.apk')" >> $GITHUB_OUTPUT

- name: Upload to App Center
  uses: wzieba/AppCenter-Github-Action@v1.3.3
  with:
    appName: my-app
    file: ${{steps.retrieve-path.outputs.path}}
```
While it does work for me, i'm an absolute noob, so please don't just copy/paste, but check for yourself
